### PR TITLE
Update link to be synd.io

### PR DESCRIPTION
**Pull request by timothymahoney**
Syndio.com has a cert error, synd.io domain looks to be the right URL :)

### CODE REVIEW

**Comment by timothymahoney** [comment]
@bvigar @tenebroso

**Review by bvigar — COMMENTED** [review]
Interesting, I didn't even know we had this site! Jon, are you good with this? Makes sense to me, I just tested it

**Comment by jonbukiewicz** [comment]
Dang I had no idea either. Thanks @timothymahoney !!

**Review by jonbukiewicz — APPROVED** [review]

**Comment by timothymahoney** [comment]
I don't have access to merge, so I'll leave that to you. It was really nice meeting the team today, hopefully we get to work together!

**Pull request merged**
